# -*- coding: utf-8 -*-
# vim: tabstop=4 shiftwidth=4 softtabstop=4
#
# oq-mapproxy-docker
# Copyright (C) 2018 GEM Foundation
#
# oq-mapproxy-docker is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# oq-mapproxy-docker is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

version: '2'
services:
  oq-geo-nginx:
    image: "nginx:1.14-alpine"
    volumes:
     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
     - "8010:8010"
    networks:
     - oq-geo-net
    restart: always
  oq-geo-mapproxy:
    image: "openquake/mapproxy-server"
    environment:
      MAPPROXY_CPU: 4
      # MAPPROXY_DEV: 'true'
    networks:
     - oq-geo-net
    volumes:
     - ./data:/io
    restart: always
    depends_on:
     - oq-geo-nginx

networks:
  oq-geo-net:
